# A visualization is a visual representation of a user’s analytical view of the data.
# You build visualizations from metrics, attributes, and optionally filters that are combined in a way to visualize a particular aspect of your data.
# The visualizations are executed over and over as fresh data gets loaded.
# Interpreting the content of a visualization is up to the user (the consumer of the visualization).
# Read more about visualisations:
# https://www.gooddata.com/developers/cloud-native/doc/cloud/create-visualizations/concepts/visualization/

type: bar_chart
id: acce1ca1-f616-469e-b9e5-7b7ab7bc7d1b

title: Products Sold by Brand and Product Line

query:
  fields:
    7696a7ea72a54759bb9080171d9863fb:
      aggregation: SUM
      using: fact/quantity
    0d46f8d3152f4a4e89ca1ece6542924b: label/Branch
    2e93b1089ec440a0b8fc4b47614ec3b8: label/City
    1176dbb1d62e4c32bd8d0d4dcd573f04: label/Product_line

metrics:
  - field: 7696a7ea72a54759bb9080171d9863fb
    format: "#,##0"

view_by:
  - 0d46f8d3152f4a4e89ca1ece6542924b
  - 2e93b1089ec440a0b8fc4b47614ec3b8

segment_by:
  - 1176dbb1d62e4c32bd8d0d4dcd573f04
