# A visualization is a visual representation of a user’s analytical view of the data.
# You build visualizations from metrics, attributes, and optionally filters that are combined in a way to visualize a particular aspect of your data.
# The visualizations are executed over and over as fresh data gets loaded.
# Interpreting the content of a visualization is up to the user (the consumer of the visualization).
# Read more about visualisations:
# https://www.gooddata.com/developers/cloud-native/doc/cloud/create-visualizations/concepts/visualization/

type: headline_chart
id: eef139b4-5a43-4aa8-9164-0cef3a2b6169

title: Products Sold

query:
  fields:
    af9ca6d761a040f8869c1a4fa2320db4:
      aggregation: SUM
      using: fact/quantity

metrics:
  - field: af9ca6d761a040f8869c1a4fa2320db4
    format: "#,##0"
